#!/usr/bin/env bash
#
# Description:
#	Displays listening ports along with the PID and name of the program
#	to which each socket belongs.
#
# Usage:
#	./show_listening_ports.sh
#
# Dependencies:
#	- netstat: This script relies on the 'netstat' command to retrieve
#	information about listening ports and associated programs.
#
# Notes:
#	- This script must be executed with Bash.
#	- Requires appropriate permissions to execute the 'netstat' command.
#


# Display listening ports along with associated PID and program name
netstat -l --program
