#!/usr/bin/env bash
#
# Description:
# Pings an IP address received as an argument 5 times.
#
# Usage:
#       ./ping_ip.sh {IP_ADDRESS}
#
# Arguments:
#       IP_ADDRESS: The IP address to ping.
#
# Exit Codes:
#       0: Successful execution.
#       1: No IP address provided.
#       2: Ping command failed.

# Check if an IP address is provided
if [ $# -lt 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

IP_ADDRESS=$1

ping -c 5 "$IP_ADDRESS" || exit 2
