#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with
# a sleep 2 in between each iteration.
# Displays "I am invincible!!!" in between each iteration.

# Define a function to handle the SIGTERM signal
sigterm_handler()
{
	echo "I am invincible!!!"
}

# Set the SIGTERM signal handler
trap 'sigterm_handler' SIGTERM

# Infinite loop to display "To infinity and beyond"
while true; do
	echo "To infinity and beyond"
	sleep 2
done
