#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# Then, displays "Hi" on the 9th iteration before "Best School".

count=0
while [ $count -lt 11 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
