#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# But, displays "bad luck" on the 4th iteration
# And, display "good luck" during the 8th iteration of the loop..

count=0
while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
