#!/usr/bin/env bash
# Displays numbers 1 to 20 using a while loop.
# But, displays "bad luck from China" on the 4th iteration
# Followed by "bad luck from Japan" on the 9th iteration
# And, Finally "bad luck from Italy" during the 17th iteration of the loop..

count=1
while [ $count -lt 21 ]
do
	echo $count
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((count++))
done
