#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
# But, displays only the part of the name after the first dash.
# And, Uses shell globbing to capture filenames..

for file in *
do
	if [ -f "$file" ]
	then
		echo "$file" | cut -d '-' -f2
	fi
done
