#!/usr/bin/env bash
#
# Description:
#       Displays all active IPv4 addresses on the machine.
#
# Usage:
#       ./1-show_attached_IPs | cat -e

# Check if ip command is available
if ! command -v ip &> /dev/null
then
        echo "Error: ip command not found."
        exit 1
fi

# Extract and display IPv4 addresses
ip -4 addr show | awk '/inet / {print $2}' | cut -d '/' -f 1
